# Site settings
title: Bomfim Jr - Desenvolvedor Front End
description: Um blog sobre desenvolvimento Front-End e UX.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bfmjr.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bomfim Jr
user_description: Desenvolvedor Front End e estudante de UX.
email: 
twitter_username: bfmjr_
github_username:  bfmjr
gplus_username:  JoãoBomfimJr
disqus_username: bmfjr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Séries
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre mim
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
